package com.example.demo;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "Payment")
public class Payment {
	private int paymentId;
	private int studentPaymentId;
	private Date paymentDate;
	private Boolean paymentDone;
	private Boolean paymentReceiptSend;
	private int amount;
	private int coursePaymentId;
	private double balance;

	public Payment() {
	}

	public double getBalance() {
		return balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public Payment(int paymentId, int studentPaymentId, Date paymentDate, Boolean paymentDone,
			Boolean paymentReceiptSend, Integer amount, int paymentid, double balance) {
		super();
		this.paymentId = paymentId;
		this.studentPaymentId = studentPaymentId;
		this.paymentDate = paymentDate;
		this.paymentDone = paymentDone;
		this.paymentReceiptSend = paymentReceiptSend;
		this.amount = amount;
		this.balance = balance;
		coursePaymentId = paymentid;
	}

	public int getCoursePaymentId() {
		return coursePaymentId;
	}

	public void setCoursePaymentId(int coursePaymentId) {
		this.coursePaymentId = coursePaymentId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public int getStudentPaymentId() {
		return studentPaymentId;
	}

	public void setStudentPaymentId(int studentPaymentId) {
		this.studentPaymentId = studentPaymentId;
	}

	public Date getPaymentDate() {
		return paymentDate;
	}

	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	public Boolean getPaymentDone() {
		return paymentDone;
	}

	public void setPaymentDone(Boolean paymentDone) {
		this.paymentDone = paymentDone;
	}

	public Boolean getPaymentReceiptSend() {
		return paymentReceiptSend;
	}

	public void setPaymentReceiptSend(Boolean paymentReceiptSend) {
		this.paymentReceiptSend = paymentReceiptSend;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
